#server setting
server:
  port:8085

#jpa setting
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hiberante.dirlect.MySQL5InnoDBDialect